Like btn
soul-ua/mobileapp pull request #4
Opened 2020-11-29 12:23 UTC by asteriosfm

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Icons/Heart.js
> +}
добавить пустую строку

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Icons/HeartFilled.js
> +}
+

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Icons/Heart.js
> +<svg
шото с отступом

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Icons/Heart.js
> +</svg>
шото с отступом

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Story/StoryFooter.tsx
> +            vote={story.vote} />
можно не переносить на отдельную  строку, а если переносить то с отступом + > - на новой строке

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +    var direction = vote.myVote===1 ? direction = 0 : direction = 1
трешак

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +    let Icon;
трешак

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +    const [ objectID , objectKind] = [vote.objectID , vote.objectKind];
const {
  objectID,
  objectKind,
} = vote;

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +            return;
spacing

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +                alert(errors[0].message);
alert will not work here (react-native does not has alert)

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +`;
новая строка

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Story/index.tsx
между импортами и первой строкой компонентов должно быть 2 отступа :) как в питоне

2020-11-29 12:42 UTC, asteriosfm commented on src/mutations/Vote/ChangeVoteMutation.ts
> +export default commit;
spacing

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +    const handleLike = ()=>{
добавить лок на случай, когда кнопку нажали во время отправки запроса

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +    const handleLike = ()=>{
google: useState react hook

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +        <LikeBtn onPress={handleLike}>
добавить пропсу isLoading={isLoading}

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +    margin:10px 10px 10px 10px;
${({isLoading=false}) => css` opacitry: 0.5 `}

2020-11-29 12:42 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +        <LikeBtn onPress={handleLike}>
activeOpacity={0.5}

2020-11-30 10:43 UTC, mrChex requested changes

2020-11-30 10:43 UTC, mrChex commented on src/mutations/Vote/ChangeVoteMutation.ts
> +export default commit;
все еще нет оступа

2020-11-30 10:43 UTC, mrChex commented on src/screens/MessengerScreen/Chat/AttachmentsModal/Galary.tsx
> +  //if () return null;
это вообще что такое?

2020-11-30 10:43 UTC, mrChex commented on src/components/Story/index.tsx
все еще один оступ

2020-11-30 10:43 UTC, mrChex commented on src/components/Story/StoryFooter.tsx
> +    </Container>);
что-то с отступом

2020-11-30 10:43 UTC, mrChex commented on src/components/Story/VotingBtn.tsx
> +
лишний отступ

2020-11-30 10:43 UTC, mrChex commented on src/components/Story/VotingBtn.tsx
> +  vote.myVote===1 ? Icon=HeartFilledIcon : Icon=HeartIcon;
что это за странная конструкция?

2020-11-30 10:43 UTC, mrChex commented on src/components/Story/VotingBtn.tsx
> +    ChangeVoteMutation(environment, objectKind, objectID, direction, (response, errors) => {
если isLoading === true запрос мутации все равно выполнится - этого быть не должно

2020-11-30 10:43 UTC, mrChex commented on src/components/Story/VotingBtn.tsx
> +        setLoading(false)
setLoading(false) только когда происходит ошибка? Это точно ожидаемое поведение?

2020-11-30 10:43 UTC, mrChex commented on src/components/Story/VotingBtn.tsx
> +    opacity:0.1;
opacity: 0.5 мы договаривались

2020-11-30 10:43 UTC, mrChex commented on src/components/Story/VotingBtn.tsx
> +  margin:10px 10px 10px 10px;
можно просто margin: 10px;

2020-11-30 10:43 UTC, mrChex commented on src/components/Story/VotingBtn.tsx
> +  justify-content-center;
тут кажется что-то не так

2020-11-30 10:43 UTC, mrChex commented on src/components/Story/VotingBtn.tsx
> +`;
не хватает отступа после логических блоков

2020-11-30 10:43 UTC, mrChex commented on src/mutations/Vote/ChangeVoteMutation.ts
> +
зачем тут пустая строка?
фигурная скобка должна быть после объявления функции

2020-11-30 10:43 UTC, mrChex commented on src/components/Story/VotingBtn.tsx
> +  return (<View accessibilityState={{disabled:isLoading}}>
можешь плз объяснить зачем это и как это работает?

2020-11-30 11:02 UTC, mrChex requested changes

2020-11-30 11:02 UTC, mrChex commented on src/components/Story/VotingBtn.tsx
> +  return (<View accessibilityState={{disabled:!isLoading}}>
мой вопрос - как это работает все еще актуальный. Ожидается какой-то текст :)

2020-11-30 11:10 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +  return (<View accessibilityState={{disabled:isLoading}}>
![Без імені11](https://user-images.githubusercontent.com/65485272/100603236-75dde580-330d-11eb-840a-ee9ea7f47a09.png)

2020-11-30 11:31 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +  return (<View accessibilityState={{disabled:!isLoading}}>
коли isLoading true - disabled=false і кнопка робоча а коли disabled=true весь контейнер не клікається

2020-11-30 12:41 UTC, mrChex requested changes

2020-11-30 12:41 UTC, mrChex commented on src/components/Story/VotingBtn.tsx
> +    isLoading===false && ChangeVoteMutation(environment, objectKind, objectID, direction, (response, errors) => {
Ні, це погано, хоча і працює. Така нотація зручна для шаблонів, коли важливо отримати результат останньої операції, але у звичайному коді має бути нормально.

тож

if(isLoading) {
  return
}

2020-11-30 12:41 UTC, mrChex commented on src/components/Story/VotingBtn.tsx
> +        return;
тобто якщо помилка - isLoading має назавжди лишитись true ?

2020-11-30 12:41 UTC, mrChex commented on src/components/Story/VotingBtn.tsx
> +  return (<Container accessibilityState={{disabled:isLoading}}>
що це робить і навіщо це потрібно?

2020-11-30 12:41 UTC, mrChex commented on src/components/Story/index.tsx
> +
навіщо тут два відступи? Між імпортами має бути максимум один

2020-11-30 12:41 UTC, mrChex commented on src/components/Story/index.tsx
тут має бути ще один відступ - між імпортами і реалізацією

2020-11-30 12:51 UTC, asteriosfm commented on src/components/Story/VotingBtn.tsx
> +  return (<Container accessibilityState={{disabled:isLoading}}>
воно дізейблило контейнер , в залежності він isLoading , але вже це не потрібно так як я прописав логіку

2020-11-30 13:55 UTC, mrChex approved these changes

2020-11-30 13:56 UTC, merged